# Generated by Django 5.1.2 on 2024-10-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'verbose_name': 'Exercise Category', 'verbose_name_plural': 'Exercise Categories'},
        ),
    ]
