# Generated by Django 5.1.2 on 2024-10-22 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'scheduled'), ('R', 'recurrent')], max_length=10),
        ),
        migrations.CreateModel(
            name='RecurringWorkoutDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('week_days', models.JSONField(blank=True, default=list)),
                ('activated', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_days', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledWorkoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dates', to='workouts.workout')),
            ],
        ),
    ]
