# Generated by Django 5.1.2 on 2024-10-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_rename_recurringworkoutdays_recurringworkoutalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringworkoutalert',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_alerts', to='workouts.workout'),
        ),
    ]
