# Generated by Django 5.1.2 on 2024-10-23 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_recurringworkoutalert_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledworkoutdate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheduledworkoutdate',
            name='time',
        ),
        migrations.AddField(
            model_name='scheduledworkoutdate',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledworkoutdate',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
